#pragma once

#include <pgmspace.h>
#include "globals.h"

// Assets Generated by  : ImageConverter 565 v2.3

namespace assets {

    extern const unsigned short flappyB[0x340] PROGMEM;
    extern const unsigned short normalB[0x340] PROGMEM;

    constexpr int maxLogoDimensions = 128;
    constexpr int numLogoMenus = 3;

    extern const unsigned short normalResizedBLogo[0x3400] PROGMEM;
    extern const unsigned short portraitLogo[0x4000] PROGMEM;
    extern const unsigned short clockLogo[0x4000] PROGMEM;

    struct MainMenuLogo {
        const unsigned short* logo;
        size_t arrSize;
        int width;
        int height;
    };

    extern MainMenuLogo logos[];

    enum logoId {
        resizedBird,
        portrait,
        hour,
    };

    MainMenuLogo getMainMenuLogo(uint8_t id);

    constexpr uint8_t PANDA_HEIGHT    = 120;
    constexpr uint8_t PANDA_WIDTH     = 120;

    extern const unsigned short Panda[0x3840] PROGMEM;

    namespace port {
        constexpr int ALL_WIDTH = 200;
        constexpr int ALL_HEIGHT = 200;
        extern const unsigned short all[0x9C40] PROGMEM;
    }

};